services:
  mysql:
    image: mysql:8.4
    restart: always
    container_name: mysql-nlw
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    ports: 
      - '3306:3306'
    networks: 
      - nlw-network
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  nlw-network:
    driver: bridge

volumes:
  mysql_data:
